### ISSUE TITLE
Update build.sh

### ISSUE THREAD

**Issue by pyroscope** [chros73/rtorrent-ps#72] opened 2017-03-12 17:31 UTC
* Newest version picks up extra version from tagging, do this: ``git tag -a PS-CH-1.2.3 -m 'whatever'``
* Logic is slightly different, I expect *existing* git clones in ``../[rakshasa-]{lib,r}torrent/``
* You could write a wrapper ``ch-build.sh`` that clones your SHAs into these dirs and then calls ``build.sh``
* Support for ``./[rakshasa-]{lib,r}torrent/`` (subdir instead of sibling) is easily added, if you need that

**Comment by chros73** [comment] 2017-03-12 17:49
Thanks for mentioning, I'll take a look.

- does it worth the hassle to only allow manually checked out versions instead of using fix commit ids?
- my only concern is about the bumped version number: although I don't know any tracker that use whitelisting instead blacklisting, but who knows maybe they start to use it after this :)

**Comment by pyroscope** [comment] 2017-03-12 17:55
AC_DEFINE(PEER_VERSION, "lt\x0D\x60", 4 byte client and version identifier for DHT)

This should be the one used in peer/tracker communication, and is untouched. Enabling tracker logging will show.

I also do not apply patches to git right now, we can collect this ticket to collect existing differences and adjust stuff accordingly.

**Comment by chros73** [comment] 2017-03-12 18:36
> This should be the one used in peer/tracker communication, and is untouched.

Ohh ... :) My bad, I learned something today as well. :)

> does it worth the hassle to only allow manually checked out versions
> we can collect this ticket to collect existing differences and adjust stuff accordingly

Now I understand what you want to achieve :) .
Well, this is the real (!) pain. I'm doing it for about half a year now (with only 1 git version), and it can be pretty messy for multiple reasons:
- created pull requests to rtorrent requires ages to get merged:
  - we have to maintain our own patches in our repos :(
- code changes in rtorrent repo (with new commits) can easily break our current patches:
  - refactoring, testing, etc. needed :(
- when we create new patches (for fixes, enhancements) can easily break our own existing patches as well! :) :
  - refactoring, testing, etc. needed :(

So, in summary: I'm against having / supporting multiple git versions, it will give us/you such a burden that we/you don't want :)
Instead, support only 1 git version (it will be enough work with this one only :) ) that is:
- stable all the time
- well tested manually before release (at least for 1 week on production)
- use branches (develop at least) for this to be able to finish / test a version before actual release
- we can use our own version number (tags as well in git) to distinguish between our own git versions:
  - nobody wants to use older version (me/you neither) when something is stable
- if new features is required (that's the common case not just 1) we can group them together (as in agile):
  - develop in feature branches, merge into develop if it's finished, then test, document, release them from master
  - and honestly, there are not so many new features needed in rtorrent but bug fixes (like the biggest one of all time: 4x read :) )
    - we won't implement e.g. webseed support (that is already done in the other libtorrent library btw)

That's how I (try to) work. :)
- flexibility for a given reasonable limit
- simplicity: we want to use our app with the less amount of interaction

I wanted to ask you before, but this seems to be the perfect time:
- do you want to work together? :) (we can have a chat on IRC about this)

**Comment by chros73** [comment] 2017-03-12 20:46
> So, in summary: I'm against having / supporting multiple git versions

I've been think about this and I just want to be clear :) :
- I'm not just against it but **we don't need** this at all :)
  - our own version numbering that I use (in the [title](https://github.com/chros73/rtorrent-ps/blob/master/build.sh#L9) of rtorrent and corresponding [tags](https://github.com/chros73/rtorrent-ps/releases) in git) is exactly for the very same purpose
  - hence we can only have the 2 commits on the build script (with the help of tags in git we can get back in time if we want)
    - in this way we don't need manual checkout either (the whole flow remains automatic)

**Comment by chros73** [comment] 2017-03-13 20:14
> our own version numbering ...

I don't know why I haven't thought of this before (that's why it's good to talk to someone :) ) :
#73 : with just couple of line of change the problem is solved (it's only on develop branch for now).

**Closed** 2017-03-14 14:15 UTC
Labels: build, no-changelog, wontfix

**Comment by chros73** [comment] 2017-03-17 11:56
>     AC_DEFINE(PEER_VERSION, "lt\x0D\x60", 4 byte client and version identifier for DHT)
> 
> This should be the one used in peer/tracker communication, and is untouched. Enabling tracker logging will show.

Well, I remembered correctly that I changed this behaviour in my [build script](https://github.com/chros73/rtorrent-ps/blob/master/build.sh#L373) for git builds in `configure.ac` files:
- that means that the client string is changed in my version! (I'm not sure about your current build script, I haven't go through it)
  - rtorrent/0.9.7/0.13.7

I'm using rtorrent this way for about half a year now, there's no issues with private/public trackers.

**Comment by chros73** [comment] 2017-05-03 10:27
@pyroscope , can you take a look at this issue? https://github.com/chros73/rtorrent-ps/issues/76
I fixed it, removing `Canvas::cleanup();` seems to solve the problem. If you don't agree with it, just let me know.

**Comment by chros73** [comment] 2017-07-17 10:09
@pyroscope , can you take a look at [this](https://github.com/chros73/rtorrent-ps/issues/89#issuecomment-315715319) compiling issue?

**Comment by chros73** [comment] 2017-07-29 06:53
@pyroscope , can you also upload the latest stable release of xmlrpc-c to your bintray?
It's the 1.43.x series, as it's in our build script, but it already got into stable, [changelog](http://xmlrpc-c.sourceforge.net/change_stable.html), and [svn commit log](https://sourceforge.net/p/xmlrpc-c/code/2912/log/?path=).
filename: `xmlrpc-c-stable-2912-src.tgz`
And we need 1 more variable in our script, e.g.: `XMLRPC_TREE=stable`

```sh
export XMLRPC_REV=2912             # stable:        v1.43.06 2016-12
svn -q checkout http://svn.code.sf.net/p/xmlrpc-c/code/stable@$XMLRPC_REV xmlrpc-c-stable-$XMLRPC_REV
```

Thanks

**Comment by chros73** [comment] 2017-08-01 17:56
@pyroscope No worries, I created mine on bintray as well.
The reason behind this is I want to create hash checking on packages after downloading.
